/* "How it's calculated" — methodology page, one entry per language. */
I18N.METHOD = {
en: {title: "How it's calculated", link: "How it's calculated", score: "How is this computed?", html: `
<h3>Where the data comes from</h3>
<p>Everything is read from Roblox's public game APIs: concurrent players, lifetime visits, favorites, votes, creator, genre, creation and update dates, server size, game passes, and — for games that publish them — social links. Player counts are read <b>every hour</b>; votes, images and descriptions once a day; groups, passes and social links twice a day (each game is re-checked at least weekly). Nothing is scraped from private sources and no player data is collected.</p>
<h3>Which games are tracked</h3>
<p>Every game found on Roblox's charts (top playing, trending, up-and-coming, fun with friends) plus a keyword search across ~220 genre and pattern terms, kept when it holds <b>100+ concurrent players</b> at discovery time. Once tracked, a game stays tracked even if it drops below that.</p>
<h3>Category and pattern signals</h3>
<p>Each game gets one category (simulator, RP, shooter, obby, tower…) and any number of pattern signals (brainrot, MM2 clone, Minecraft-derived, "Steal a X", "+1 per click", tower climb, RNG/gacha, borrowed IP, original flagship…). Around a third are hand-reviewed; the rest are classified by rules on name, description and genre and shown with an <i>auto</i> mark. Hand corrections always win over rules.</p>
<h3>Trends (24h · 7d · 30d)</h3>
<p>A change compares the current reading with the reading closest to 1, 7 or 30 days ago <b>at the same time of day (±3 h)</b>, so a Saturday evening is never compared with a Tuesday morning. A game is <b>rising</b> at +15 % or more over 7 days, <b>falling</b> at −15 % or less, and <b>new</b> when created less than 30 days ago. Trends stay empty until enough history exists.</p>
<h3>Opportunity score (0–100)</h3>
<p>A research shortlist, not advice. Points: <b>momentum</b> up to 35 (7-day change, 24 h as tie-break), <b>rating</b> up to 20 (like ratio), <b>scale</b> up to 15 (players now, log scale), <b>freshness</b> up to 15 (age and last update), <b>engagement</b> up to 15 (visits per day relative to players). Adjustments: +8 original flagship, +4 group-owned, −10 copy of another hit, −12 borrowed IP, −8 saturated pattern (brainrot, "Steal a X", "+1 per click", tower climb, MM2 clone), −3 when classified automatically.</p>
<h3>Business estimates</h3>
<p><b>Daily players (DAU)</b> ≈ average concurrent players over the last 24 h × 12, a common Roblox ratio. <b>Developer earnings</b> assume $6–18 per month per average concurrent player after Roblox's cut, calibrated on publicly reported cases, × 0.5 when the game has no passes and × 1.3 when it has many or expensive ones. <b>Typical asking price</b> = 12–24 × monthly earnings, the usual range in the buyer market for small and mid-size games. Roblox publishes none of this; treat all three as a starting range for due diligence.</p>
<h3>Studios</h3>
<p>Games are grouped by their owner (group or user account). The 7-day change of a studio is weighted by players (summed players now vs. summed players a week ago), rating is weighted by players, earnings are summed, and <b>concentration</b> is the share of the studio's players held by its main game.</p>
<h3>Discord alerts</h3>
<p>After every reading: <b>spike</b> +50 % vs. the same time yesterday with 2,000+ players; <b>drop</b> −40 % from 5,000+; <b>newcomer</b> added today with 5,000+; <b>watchlist</b> ±30 %; <b>milestone</b> first time crossing 50K, 100K, 250K, 500K, 1M or 2M. At most 10 per reading, one per game and type per 24 h.</p>
<h3>Known limits</h3>
<p>Concurrent players include bots and event spikes Roblox has not yet filtered. Ratings lag: a game can be dying with a 95 % like ratio. Automatic classification is wrong for a share of games. Earnings depend on monetization design far more than on player counts. History starts on the day a game was added, so long-range charts are empty for recent additions.</p>`},

es: {title: "Cómo se calcula", link: "Cómo se calcula", score: "¿Cómo se calcula?", html: `
<h3>De dónde salen los datos</h3>
<p>Todo se lee de las APIs públicas de juegos de Roblox: jugadores concurrentes, visitas totales, favoritos, votos, creador, género, fechas de creación y actualización, tamaño de servidor, game passes y — en los juegos que las publican — redes sociales. Los jugadores se leen <b>cada hora</b>; votos, imágenes y descripciones una vez al día; grupos, passes y redes dos veces al día (cada juego se revisa al menos una vez por semana). No se extrae nada de fuentes privadas ni se recogen datos de jugadores.</p>
<h3>Qué juegos se rastrean</h3>
<p>Todos los que aparecen en las listas de Roblox (más jugados, tendencia, emergentes, con amigos) más una búsqueda por ~220 palabras clave de género y patrón; se guarda cada juego que tenga <b>100+ jugadores concurrentes</b> al descubrirlo. Una vez dentro, el juego se sigue aunque baje de esa cifra.</p>
<h3>Categoría y señales de patrón</h3>
<p>Cada juego tiene una categoría (simulador, RP, shooter, obby, torre…) y las señales de patrón que correspondan (brainrot, clon de MM2, derivado de Minecraft, "Steal a X", "+1 por click", torre, RNG/gacha, IP ajena, original insignia…). Alrededor de un tercio están revisados a mano; el resto se clasifica con reglas sobre nombre, descripción y género y lleva la marca <i>auto</i>. Las correcciones manuales siempre ganan a las reglas.</p>
<h3>Tendencias (24h · 7d · 30d)</h3>
<p>Un cambio compara la lectura actual con la más cercana a hace 1, 7 o 30 días <b>a la misma hora del día (±3 h)</b>, así nunca se compara un sábado por la noche con un martes por la mañana. Un juego está <b>subiendo</b> con +15 % o más en 7 días, <b>bajando</b> con −15 % o menos, y es <b>nuevo</b> si se creó hace menos de 30 días. Las tendencias quedan vacías hasta que haya historial suficiente.</p>
<h3>Puntaje de oportunidad (0–100)</h3>
<p>Una lista para investigar, no un consejo. Puntos: <b>impulso</b> hasta 35 (cambio en 7 días; 24 h como desempate), <b>valoración</b> hasta 20 (proporción de likes), <b>escala</b> hasta 15 (jugadores ahora, escala logarítmica), <b>frescura</b> hasta 15 (edad y última actualización), <b>enganche</b> hasta 15 (visitas por día respecto a jugadores). Ajustes: +8 original insignia, +4 propiedad de grupo, −10 copia de otro éxito, −12 IP ajena, −8 patrón saturado (brainrot, "Steal a X", "+1 por click", torre, clon de MM2), −3 si se clasificó automáticamente.</p>
<h3>Estimaciones de negocio</h3>
<p><b>Jugadores diarios (DAU)</b> ≈ jugadores concurrentes promedio de las últimas 24 h × 12, proporción habitual en Roblox. <b>Ganancia del desarrollador</b> asume $6–18 al mes por jugador concurrente promedio tras la comisión de Roblox, calibrado con casos públicos, × 0,5 si el juego no tiene passes y × 1,3 si tiene muchos o caros. <b>Precio típico de venta</b> = 12–24 × la ganancia mensual, el rango habitual del mercado de compraventa para juegos pequeños y medianos. Roblox no publica nada de esto; toma los tres como rango inicial para tu diligencia.</p>
<h3>Estudios</h3>
<p>Los juegos se agrupan por dueño (grupo o cuenta personal). El cambio 7d de un estudio se pondera por jugadores (suma de jugadores ahora frente a suma hace una semana), la valoración se pondera por jugadores, las ganancias se suman, y la <b>concentración</b> es la parte de los jugadores del estudio que tiene su juego principal.</p>
<h3>Alertas de Discord</h3>
<p>Tras cada lectura: <b>subida</b> +50 % respecto a la misma hora de ayer con 2.000+ jugadores; <b>caída</b> −40 % desde 5.000+; <b>nuevo</b> añadido hoy con 5.000+; <b>lista de seguimiento</b> ±30 %; <b>hito</b> la primera vez que cruza 50K, 100K, 250K, 500K, 1M o 2M. Máximo 10 por lectura, una por juego y tipo cada 24 h.</p>
<h3>Límites conocidos</h3>
<p>Los jugadores concurrentes incluyen bots y picos de eventos que Roblox aún no ha filtrado. La valoración va con retraso: un juego puede estar muriendo con 95 % de likes. La clasificación automática se equivoca en parte de los juegos. La ganancia depende mucho más del diseño de monetización que del número de jugadores. El historial empieza el día en que se añadió el juego, así que las gráficas largas están vacías en los añadidos recientes.</p>`},

pt: {title: "Como é calculado", link: "Como é calculado", score: "Como isto é calculado?", html: `
<h3>De onde vêm os dados</h3><p>Tudo é lido das APIs públicas de jogos do Roblox: jogadores simultâneos, visitas, favoritos, votos, criador, gênero, datas, tamanho de servidor, game passes e redes sociais (quando publicadas). Jogadores são lidos <b>a cada hora</b>; votos e imagens uma vez ao dia; grupos, passes e redes duas vezes ao dia. Nenhum dado de jogadores é coletado.</p>
<h3>Quais jogos são rastreados</h3><p>Todos os das listas do Roblox mais uma busca por ~220 palavras-chave, mantidos quando têm <b>100+ jogadores simultâneos</b> ao serem descobertos.</p>
<h3>Categoria e sinais de padrão</h3><p>Uma categoria por jogo e quantos sinais de padrão se apliquem (brainrot, clone de MM2, derivado de Minecraft, "Steal a X", torre, RNG/gacha, IP alheia, original…). Cerca de um terço é revisado à mão; o resto é classificado por regras e marcado como <i>auto</i>.</p>
<h3>Tendências (24h · 7d · 30d)</h3><p>Compara a leitura atual com a mais próxima de 1, 7 ou 30 dias atrás <b>no mesmo horário (±3 h)</b>. <b>Subindo</b> a partir de +15 % em 7 dias, <b>caindo</b> a partir de −15 %, <b>novo</b> com menos de 30 dias.</p>
<h3>Pontuação de oportunidade (0–100)</h3><p>Lista de pesquisa, não conselho. <b>Impulso</b> até 35, <b>avaliação</b> até 20, <b>escala</b> até 15, <b>frescor</b> até 15, <b>engajamento</b> até 15. Ajustes: +8 original, +4 de grupo, −10 cópia, −12 IP alheia, −8 padrão saturado, −3 classificação automática.</p>
<h3>Estimativas de negócio</h3><p><b>DAU</b> ≈ média de simultâneos nas últimas 24 h × 12. <b>Receita</b> assume US$ 6–18/mês por jogador simultâneo médio após a comissão do Roblox (× 0,5 sem passes, × 1,3 com muitos). <b>Preço típico</b> = 12–24 × receita mensal. O Roblox não publica nada disso; use como faixa inicial.</p>
<h3>Estúdios</h3><p>Jogos agrupados por dono. Variação 7d e avaliação ponderadas por jogadores, receita somada, <b>concentração</b> = parte dos jogadores no jogo principal.</p>
<h3>Alertas do Discord</h3><p>Após cada leitura: <b>alta</b> +50 % com 2.000+; <b>queda</b> −40 % de 5.000+; <b>novo</b> com 5.000+; <b>lista</b> ±30 %; <b>marco</b> ao cruzar 50K…2M. Máximo 10 por leitura, um por jogo e tipo a cada 24 h.</p>
<h3>Limites conhecidos</h3><p>Simultâneos incluem bots e picos de eventos; avaliações atrasam; a classificação automática erra em parte dos jogos; a receita depende mais da monetização do que do número de jogadores; o histórico começa no dia em que o jogo foi adicionado.</p>`},

fr: {title: "Méthode de calcul", link: "Méthode de calcul", score: "Comment est-ce calculé ?", html: `
<h3>D’où viennent les données</h3><p>Tout est lu depuis les API publiques de Roblox : joueurs simultanés, visites, favoris, votes, créateur, genre, dates, taille des serveurs, game passes et liens sociaux (s’ils sont publiés). Les joueurs sont lus <b>chaque heure</b> ; votes et images une fois par jour ; groupes, passes et liens deux fois par jour. Aucune donnée de joueur n’est collectée.</p>
<h3>Jeux suivis</h3><p>Tous ceux des classements Roblox plus une recherche sur ~220 mots-clés, conservés s’ils ont <b>100+ joueurs simultanés</b> à la découverte.</p>
<h3>Catégorie et signaux</h3><p>Une catégorie par jeu et autant de signaux que nécessaire (brainrot, clone de MM2, dérivé de Minecraft, « Steal a X », tour, RNG/gacha, IP empruntée, original…). Environ un tiers est vérifié à la main ; le reste est classé par règles et marqué <i>auto</i>.</p>
<h3>Tendances (24h · 7j · 30j)</h3><p>Comparaison avec la lecture la plus proche d’il y a 1, 7 ou 30 jours <b>à la même heure (±3 h)</b>. <b>En hausse</b> à partir de +15 % sur 7 jours, <b>en baisse</b> à partir de −15 %, <b>nouveau</b> si créé depuis moins de 30 jours.</p>
<h3>Score d’opportunité (0–100)</h3><p>Une liste de recherche, pas un conseil. <b>Élan</b> jusqu’à 35, <b>note</b> 20, <b>échelle</b> 15, <b>fraîcheur</b> 15, <b>engagement</b> 15. Ajustements : +8 original, +4 groupe, −10 copie, −12 IP empruntée, −8 motif saturé, −3 classement automatique.</p>
<h3>Estimations</h3><p><b>DAU</b> ≈ moyenne des simultanés sur 24 h × 12. <b>Revenus</b> : 6–18 $/mois par joueur simultané moyen après la part de Roblox (× 0,5 sans passes, × 1,3 avec beaucoup). <b>Prix demandé typique</b> = 12–24 × revenus mensuels. Roblox ne publie rien de tout cela.</p>
<h3>Studios</h3><p>Jeux regroupés par propriétaire. Variation 7j et note pondérées par joueurs, revenus additionnés, <b>concentration</b> = part des joueurs sur le jeu principal.</p>
<h3>Alertes Discord</h3><p>Après chaque lecture : <b>hausse</b> +50 % avec 2 000+ ; <b>baisse</b> −40 % depuis 5 000+ ; <b>nouveau</b> avec 5 000+ ; <b>liste</b> ±30 % ; <b>palier</b> 50K…2M. Max 10 par lecture, une par jeu et type par 24 h.</p>
<h3>Limites connues</h3><p>Les simultanés incluent bots et pics d’événements ; les notes sont en retard ; le classement automatique se trompe parfois ; les revenus dépendent surtout de la monétisation ; l’historique commence le jour de l’ajout.</p>`},

de: {title: "So wird gerechnet", link: "So wird gerechnet", score: "Wie wird das berechnet?", html: `
<h3>Woher die Daten kommen</h3><p>Alles stammt aus den öffentlichen Spiel-APIs von Roblox: gleichzeitige Spieler, Besuche, Favoriten, Stimmen, Ersteller, Genre, Daten, Servergröße, Game Passes und Social-Links (falls veröffentlicht). Spieler werden <b>stündlich</b> gelesen, Stimmen und Bilder täglich, Gruppen, Passes und Links zweimal täglich. Es werden keine Spielerdaten erhoben.</p>
<h3>Welche Spiele erfasst werden</h3><p>Alle aus den Roblox-Charts plus eine Suche über ~220 Stichwörter; behalten wird, was bei der Entdeckung <b>100+ gleichzeitige Spieler</b> hat.</p>
<h3>Kategorie und Muster</h3><p>Eine Kategorie pro Spiel und beliebig viele Mustersignale (Brainrot, MM2-Klon, Minecraft-Ableger, „Steal a X“, Turm, RNG/Gacha, fremde IP, Original…). Etwa ein Drittel ist handgeprüft; der Rest wird per Regeln klassifiziert und als <i>auto</i> markiert.</p>
<h3>Trends (24h · 7T · 30T)</h3><p>Vergleich mit der Messung, die 1, 7 oder 30 Tage zurückliegt, <b>zur gleichen Tageszeit (±3 h)</b>. <b>Steigend</b> ab +15 % in 7 Tagen, <b>fallend</b> ab −15 %, <b>neu</b> unter 30 Tagen.</p>
<h3>Chancen-Score (0–100)</h3><p>Recherche-Liste, keine Empfehlung. <b>Momentum</b> bis 35, <b>Bewertung</b> 20, <b>Größe</b> 15, <b>Frische</b> 15, <b>Bindung</b> 15. Anpassungen: +8 Original, +4 Gruppe, −10 Kopie, −12 fremde IP, −8 gesättigtes Muster, −3 automatische Einstufung.</p>
<h3>Geschäftsschätzungen</h3><p><b>DAU</b> ≈ Ø gleichzeitige Spieler der letzten 24 h × 12. <b>Einnahmen</b>: 6–18 $/Monat je durchschnittlichem gleichzeitigem Spieler nach Roblox-Anteil (× 0,5 ohne Passes, × 1,3 mit vielen). <b>Üblicher Preis</b> = 12–24 × Monatseinnahmen. Roblox veröffentlicht nichts davon.</p>
<h3>Studios</h3><p>Spiele nach Besitzer gruppiert. 7T-Änderung und Bewertung spielergewichtet, Einnahmen summiert, <b>Konzentration</b> = Anteil der Spieler im Hauptspiel.</p>
<h3>Discord-Alarme</h3><p>Nach jeder Messung: <b>Anstieg</b> +50 % bei 2.000+; <b>Einbruch</b> −40 % ab 5.000+; <b>Neuzugang</b> mit 5.000+; <b>Liste</b> ±30 %; <b>Meilenstein</b> 50K…2M. Max. 10 pro Messung, einer je Spiel und Typ pro 24 h.</p>
<h3>Bekannte Grenzen</h3><p>Spielerzahlen enthalten Bots und Event-Spitzen; Bewertungen hinken nach; die automatische Einstufung irrt teilweise; Einnahmen hängen vor allem von der Monetarisierung ab; die Historie beginnt am Tag der Aufnahme.</p>`},

it: {title: "Come si calcola", link: "Come si calcola", score: "Come viene calcolato?", html: `
<h3>Da dove vengono i dati</h3><p>Tutto è letto dalle API pubbliche dei giochi Roblox: giocatori simultanei, visite, preferiti, voti, creatore, genere, date, dimensione server, game pass e link social (se pubblicati). I giocatori si leggono <b>ogni ora</b>; voti e immagini una volta al giorno; gruppi, pass e link due volte al giorno. Nessun dato dei giocatori viene raccolto.</p>
<h3>Quali giochi sono tracciati</h3><p>Tutti quelli nelle classifiche Roblox più una ricerca su ~220 parole chiave, tenuti se hanno <b>100+ giocatori simultanei</b> alla scoperta.</p>
<h3>Categoria e segnali</h3><p>Una categoria per gioco e i segnali di pattern che servono (brainrot, clone di MM2, derivato da Minecraft, "Steal a X", torre, RNG/gacha, IP altrui, originale…). Circa un terzo è rivisto a mano; il resto è classificato da regole e marcato <i>auto</i>.</p>
<h3>Tendenze (24h · 7g · 30g)</h3><p>Confronto con la lettura più vicina a 1, 7 o 30 giorni fa <b>alla stessa ora (±3 h)</b>. <b>In crescita</b> da +15 % in 7 giorni, <b>in calo</b> da −15 %, <b>nuovo</b> sotto i 30 giorni.</p>
<h3>Punteggio di opportunità (0–100)</h3><p>Una lista di ricerca, non un consiglio. <b>Slancio</b> fino a 35, <b>valutazione</b> 20, <b>scala</b> 15, <b>freschezza</b> 15, <b>coinvolgimento</b> 15. Aggiustamenti: +8 originale, +4 gruppo, −10 copia, −12 IP altrui, −8 pattern saturo, −3 classificazione automatica.</p>
<h3>Stime di business</h3><p><b>DAU</b> ≈ media simultanei ultime 24 h × 12. <b>Ricavi</b>: 6–18 $/mese per giocatore simultaneo medio dopo la quota Roblox (× 0,5 senza pass, × 1,3 con molti). <b>Prezzo tipico</b> = 12–24 × ricavi mensili. Roblox non pubblica nulla di tutto ciò.</p>
<h3>Studi</h3><p>Giochi raggruppati per proprietario. Variazione 7g e valutazione pesate sui giocatori, ricavi sommati, <b>concentrazione</b> = quota di giocatori nel gioco principale.</p>
<h3>Avvisi Discord</h3><p>Dopo ogni lettura: <b>picco</b> +50 % con 2.000+; <b>calo</b> −40 % da 5.000+; <b>novità</b> con 5.000+; <b>lista</b> ±30 %; <b>traguardo</b> 50K…2M. Max 10 per lettura, uno per gioco e tipo ogni 24 h.</p>
<h3>Limiti noti</h3><p>I simultanei includono bot e picchi da eventi; le valutazioni ritardano; la classificazione automatica sbaglia su parte dei giochi; i ricavi dipendono soprattutto dalla monetizzazione; lo storico parte dal giorno dell’aggiunta.</p>`},

ru: {title: "Как это считается", link: "Как это считается", score: "Как это считается?", html: `
<h3>Откуда данные</h3><p>Всё берётся из публичных API Roblox: онлайн, визиты, избранное, голоса, создатель, жанр, даты, размер сервера, геймпассы и соцсети (если опубликованы). Онлайн читается <b>каждый час</b>; голоса и картинки раз в день; группы, пассы и ссылки дважды в день. Данные игроков не собираются.</p>
<h3>Какие игры отслеживаются</h3><p>Все из чартов Roblox плюс поиск по ~220 ключевым словам; сохраняются игры со <b>100+ онлайн</b> на момент обнаружения.</p>
<h3>Категория и паттерны</h3><p>Одна категория и любое число сигналов (brainrot, клон MM2, производное от Minecraft, «Steal a X», башня, RNG/гача, чужая IP, оригинал…). Около трети проверено вручную; остальное классифицировано правилами и помечено <i>auto</i>.</p>
<h3>Тренды (24ч · 7д · 30д)</h3><p>Сравнение с ближайшим замером 1, 7 или 30 дней назад <b>в то же время суток (±3 ч)</b>. <b>Рост</b> от +15 % за 7 дней, <b>падение</b> от −15 %, <b>новая</b> — младше 30 дней.</p>
<h3>Балл возможности (0–100)</h3><p>Список для изучения, не совет. <b>Импульс</b> до 35, <b>рейтинг</b> 20, <b>масштаб</b> 15, <b>свежесть</b> 15, <b>вовлечённость</b> 15. Поправки: +8 оригинал, +4 группа, −10 копия, −12 чужая IP, −8 перенасыщенный паттерн, −3 автоклассификация.</p>
<h3>Оценки бизнеса</h3><p><b>DAU</b> ≈ средний онлайн за 24 ч × 12. <b>Доход</b>: 6–18 $/мес на среднего одновременного игрока после доли Roblox (× 0,5 без пассов, × 1,3 при многих). <b>Типичная цена</b> = 12–24 × месячного дохода. Roblox ничего из этого не публикует.</p>
<h3>Студии</h3><p>Игры сгруппированы по владельцу. Изменение за 7д и рейтинг взвешены по игрокам, доход суммируется, <b>концентрация</b> = доля игроков в главной игре.</p>
<h3>Оповещения Discord</h3><p>После каждого замера: <b>рост</b> +50 % при 2 000+; <b>падение</b> −40 % от 5 000+; <b>новинка</b> с 5 000+; <b>список</b> ±30 %; <b>рубеж</b> 50K…2M. Не более 10 за замер, одно на игру и тип за 24 ч.</p>
<h3>Ограничения</h3><p>Онлайн включает ботов и всплески событий; рейтинг запаздывает; автоклассификация ошибается; доход зависит прежде всего от монетизации; история начинается со дня добавления.</p>`},

ja: {title: "計算方法", link: "計算方法", score: "どう計算している？", html: `
<h3>データの出所</h3><p>すべてRobloxの公開ゲームAPIから取得：同時接続数、累計訪問、お気に入り、評価、制作者、ジャンル、日付、サーバー人数、ゲームパス、ソーシャルリンク（公開されている場合）。同時接続数は<b>毎時</b>、評価と画像は1日1回、グループ・パス・リンクは1日2回読み取ります。プレイヤーの個人データは収集しません。</p>
<h3>対象ゲーム</h3><p>Robloxの各チャートに載るゲームと約220のキーワード検索で見つかり、発見時に<b>同時接続100人以上</b>のゲーム。</p>
<h3>カテゴリとパターン</h3><p>各ゲームに1つのカテゴリと必要な数のパターン信号（brainrot、MM2クローン、Minecraft派生、「Steal a X」、タワー、RNG/ガチャ、他社IP、オリジナル…）。約3分の1は手作業で確認、残りはルールで分類し<i>auto</i>と表示。</p>
<h3>トレンド（24h · 7d · 30d）</h3><p>1・7・30日前の<b>同じ時間帯（±3時間）</b>の読み取りと比較。7日で+15%以上なら<b>上昇</b>、−15%以下なら<b>下降</b>、作成30日未満は<b>新着</b>。</p>
<h3>機会スコア（0–100）</h3><p>調査用リストであり助言ではありません。<b>勢い</b>最大35、<b>評価</b>20、<b>規模</b>15、<b>新しさ</b>15、<b>定着</b>15。調整：オリジナル+8、グループ所有+4、コピー−10、他社IP−12、飽和パターン−8、自動分類−3。</p>
<h3>ビジネス推定</h3><p><b>DAU</b>≈直近24時間の平均同時接続×12。<b>収益</b>は平均同時接続1人あたり月6–18ドル（Robloxの取り分控除後、パスなし×0.5、多い場合×1.3）。<b>一般的な売却価格</b>＝月収益の12–24倍。Robloxはこれらを公開していません。</p>
<h3>スタジオ</h3><p>所有者ごとにゲームをまとめ、7日変化と評価はプレイヤー数で加重、収益は合算、<b>集中度</b>＝主力ゲームが占めるプレイヤーの割合。</p>
<h3>Discord通知</h3><p>各読み取り後：<b>急上昇</b>+50%（2,000人以上）、<b>急落</b>−40%（5,000人以上から）、<b>新着</b>5,000人以上、<b>ウォッチリスト</b>±30%、<b>節目</b>50K…2M。1回最大10件、ゲーム・種類ごとに24時間に1件。</p>
<h3>既知の限界</h3><p>同時接続にはボットやイベントの急増が含まれる。評価は遅れて反映される。自動分類は一部で誤る。収益は人数より収益化設計に依存する。履歴は追加日から始まる。</p>`}
};
